AccessAzureStorage/Models/EmployeeData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Table;
namespace AccessAzureStorage.Models
{
    public class EmployeeData : TableEntity
    {
        public EmployeeData(string EmpId, string Name)
        {
            this.PartitionKey = EmpId;
            this.RowKey = Name;
        }

        public EmployeeData() { }
        public string id { get; set; }
        public string Name { get; set; }
        public string EmployeeId { get; set; }
        public string Domain { get; set; }
        public string Email { get; set; }
    }
}

AccessAzureStorage/Controllers/BlobController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Blob;
using System.Configuration;

namespace AccessAzureStorage.Controllers
{
    public class BlobController : Controller
    {
        private static CloudStorageAccount CloudStorageAccount = 
            CloudStorageAccount.Parse(ConfigurationManager.AppSettings.Get("StorageConnectionString"));

        private static CloudBlobClient Client = CloudStorageAccount.CreateCloudBlobClient();
        
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Upload()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Upload(HttpPostedFileBase File)
        {
            try
            {
                CloudBlobContainer Container = Client.GetContainerReference("file-container");
                Container.CreateIfNotExists();

                CloudBlockBlob Blob = Container.GetBlockBlobReference(File.FileName);
                Blob.UploadFromStream(File.InputStream);
            }
            catch (Exception)
            {
                return View("Error");
            }
            return View("Success");
        }
    }
}

AccessAzureStorage/Controllers/FileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AccessAzureStorage.Controllers
{
    public class FileController : Controller
    {
        // GET: File
        public ActionResult Index()
        {
            return View();
        }
    }
}

AccessAzureStorage/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.WindowsAzure.MobileServices;
using AccessAzureStorage.Models;
using System.Net.Http;
using System.Configuration;

namespace AccessAzureStorage.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Upload()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Upload(EmployeeData Record)
        {
            var client = new MobileServiceClient(ConfigurationManager.AppSettings.Get("MobileAppUrl"));

            IMobileServiceTable<EmployeeData> EmployeeTable = client.GetTable<EmployeeData>();

            try
            {
                Record.id = new Random().Next(1, 1000).ToString();
                if(Record !=null && EmployeeTable.InsertAsync(Record)!=null)
                {
                    return View("Success");
                }
            }
            catch (Exception)
            {
                return View("Error");
            }

            return View("Index");
        }
    }
}

AccessAzureStorage/Controllers/QueueController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Configuration;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Queue;
using Microsoft.ServiceBus.Messaging;

namespace AccessAzureStorage.Controllers
{
    public class QueueController : Controller
    {
        private CloudStorageAccount StorageAccount = CloudStorageAccount.Parse(ConfigurationManager.AppSettings.Get("StorageConnectionString"));

        public ActionResult Index()
        {
            ViewBag.Message = string.Empty;
            return View();
        }

        [HttpPost]
        public ActionResult Index(string Message)
        {
            string connectionString = ConfigurationManager.AppSettings.Get("ServiceBusQueue");
            try
            {
                string action = Request.Form.Get("action");
                CloudQueueClient SQueueClient = StorageAccount.CreateCloudQueueClient();
                QueueClient SBQueueClient = QueueClient.CreateFromConnectionString(connectionString);
                CloudQueue Queue = SQueueClient.GetQueueReference("hp532queue");
                Queue.CreateIfNotExists();
                switch (action)
                {
                    case "Send Message":
                        Queue.AddMessage(new CloudQueueMessage(Message));
                        SBQueueClient.Send(new BrokeredMessage(Message));
                        break;
                    case "Receive Message":
                        ViewBag.Message = SBQueueClient.Receive().GetBody<string>();
                        if(string.IsNullOrWhiteSpace(SBQueueClient.Receive().GetBody<string>()))
                            ViewBag.Message = Queue.GetMessage().AsString;
                        break;
                    default:
                        return View("Error");
                }
                return View("Index");
            }
            catch (Exception)
            {
                return View("Error");
            }
        }
    }
}

AccessAzureStorage/Controllers/TableController.cs
using AccessAzureStorage.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Table;
using System.Configuration;

namespace AccessAzureStorage.Controllers
{
    public class TableController : Controller
    {
        private CloudStorageAccount StorageAccount = CloudStorageAccount.Parse(ConfigurationManager.AppSettings.Get("StorageConnectionString"));
        
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Upload()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Upload(EmployeeData Records)
        {
            try
            {
                CloudTableClient TableClient = StorageAccount.CreateCloudTableClient();
                CloudTable DataEntity = TableClient.GetTableReference("Employees");
                DataEntity.CreateIfNotExists();

                if (Records.EmployeeId != null && Records.Name != null)
                {
                    Records.PartitionKey = Records.EmployeeId;
                    Records.RowKey = Records.Name;
                    Records.Timestamp = DateTime.Now;
                    TableOperation Insert = TableOperation.InsertOrReplace(Records);
                    DataEntity.Execute(Insert);
                }
            }
            catch (Exception)
            {
                return View("Error");
            }
            return View("Success");
        }
    }
}

AccessAzureStorage/Views/Blob/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div class="col-md-10 col-md-offset-1">
    <div class="banner-text text-center">
        <h1>Blob Services</h1>
        <span class="btn btn-large">@Html.ActionLink("Upload File","Upload")</span>
</div>
</div>

AccessAzureStorage/Views/Blob/Upload.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Upload</title>
</head>
<body>
    @using (Html.BeginForm("Upload", "Blob",FormMethod.Post, new { enctype = "multipart/form-data" }))
    {

        <div>
            @Html.TextBox("file", "", new { type = "file" }) <br />
            <input type="submit" value="Upload" />
        </div>


    }
    
</body>
</html>

AccessAzureStorage/Views/File/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div class="col-md-10 col-md-offset-1">
    <div class="banner-text text-center">
        <h1>File Services</h1>
        <span class="btn btn-large">@Html.ActionLink("Upload File","Upload")</span> <br /> <br />
        <span class="btn btn-large">@Html.ActionLink("Download File", "Download")</span>
</div>
</div>

AccessAzureStorage/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div class="col-md-10 col-md-offset-1">
    <div class="banner-text text-center">
        <h1>Azure Storage Options</h1>
        <h3>You can use<strong> Azure storage</strong> to store your files and lot of other stuff.</h3>
    </div>
</div>

AccessAzureStorage/Views/Home/Upload.cshtml
@model AccessAzureStorage.Models.EmployeeData

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Upload</title>
</head>
<body>
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>EmployeeData</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.EmployeeId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.EmployeeId, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.EmployeeId, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Domain, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Domain, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Domain, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

AccessAzureStorage/Views/Queue/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div class="col-md-10 col-md-offset-1">
    <div class="banner-text text-center">
        <h1>Queue Services</h1>
        @using (Html.BeginForm("Index", "Queue", FormMethod.Post))
        {
            <input type="text" class="form-control" name="Message" placeholder="Input/Output" value="@ViewBag.Message"><br/><br/>
            <input type="submit" name="action" value="Send Message" class="btn btn-large">
            <input type="submit" name="action" value="Receive Message" class="btn btn-large">
        }
</div>
</div>

AccessAzureStorage/Views/Shared/Success.cshtml
@{
    ViewBag.Title = "Successful";
}

<div class="col-md-10 col-md-offset-1">
    <div class="banner-text text-center">
        <h1>Success</h1>
        Action has been performed Successfully !!!
    </div>
</div>

AccessAzureStorage/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html class="js flexbox flexboxlegacy canvas canvastext webgl touch geolocation postmessage websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms csstransforms3d csstransitions fontface no-generatedcontent video audio localstorage sessionstorage webworkers applicationcache svg inlinesvg smil svgclippaths js flexbox flexboxlegacy canvas canvastext webgl touch geolocation postmessage websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms csstransforms3d csstransitions fontface no-generatedcontent video audio localstorage sessionstorage webworkers applicationcache svg inlinesvg smil svgclippaths" lang="">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>HpStorage</title>
    <link rel="stylesheet" href="../../StylePages/Css/bootstrap.min.css">
    <link rel="stylesheet" href="../../StylePages/Css/flexslider.css">
    <link rel="stylesheet" href="../../StylePages/Css/jquery.fancybox.css">
    <link rel="stylesheet" href="../../StylePages/Css/main.css">
    <link rel="stylesheet" href="../../StylePages/Css/responsive.css">
    <link rel="stylesheet" href="../../StylePages/Css/animate.min.css">
    <link rel="stylesheet" href="../../StylePages/Css/font-awesome.min.css">
    <style type="text/css">
        .fancybox-margin {
            margin-right: 17px;
        }
    </style>
    <style type="text/css">
        .fancybox-margin {
            margin-right: 17px;
        }
    </style>
</head>
<body>
    <section class="banner" role="banner">
        <header id="header" class="">
            <div class="header-content clearfix">
                <a class="logo" href="@Url.Action("Index","Home")"><img src="../../StylePages/Image/logo.png" alt=""></a>
                <nav class="navigation" role="navigation">
                    <ul class="primary-nav">
                        <li>@Html.ActionLink("Blob", "Index", "Blob")</li>
                        <li>@Html.ActionLink("File", "Index", "File")</li>
                        <li>@Html.ActionLink("Table", "Index", "Table")</li>
                        <li>@Html.ActionLink("Queue", "Index", "Queue")</li>
                    </ul>
                </nav>
                <a href="file:///C:/Users/emnis/Downloads/hp-Storage/index.html#" class="nav-toggle">Menu<span></span></a>
            </div><!-- header content -->
        </header><!-- header -->

        <div class="container">
            @RenderBody()
        </div>
    </section>

    <footer class="footer">
        <!-- footer top -->
        <div class="footer-bottom">
            <div class="container">
                <div class="col-md-12">
                    <p>Copyright © 2018 hp532. All Rights Reserved.</p>
                </div>
            </div>
        </div>
    </footer>
    <!-- footer -->
</body>
</html>

AccessAzureStorage/Views/Table/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div class="col-md-10 col-md-offset-1">
    <div class="banner-text text-center">
        <h1>Table Services</h1>
        <span class="btn btn-large">@Html.ActionLink("Store Data","Upload")</span>
        <span class="btn btn-large">@Html.ActionLink("Store Data On Mobile", "Upload","Home")</span>
</div>
</div>